version: '0.1'
services:
  web:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8002"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=django-project.settings
      - DEBUG=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  db:
    image: postgres
    environment:
      - POSTGRES_DB=microBlogDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2404
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis

volumes:
  pgdata:
